hichip.py:
  name: hichip
  looper_args: True
  arguments:
    "--sample-name": sample_name
    "--genome": genome
    "--input": data_source

    #"--input2": read2
    "--single-or-paired": read_type
  resources:
    default:
      file_size: "0"
      cores: "4"
      mem: "16000"
      time: "2-00:00:00"
      partition: "longq"
